name: Pull Request

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  formalities:
    name: Validate PR formalities
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          requireScope: false
          ignoreLabels: |
            dependabot

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up mise
        uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3.5.1

      - name: Lint
        run: mise lint

      - name: Run go mod tidy
        run: go mod tidy

      - name: Run go generate
        run: mise gogen

      - name: Check for changes
        run: |
          if ! git diff --exit-code; then
            echo "::error::Files are not up to date. Please run 'go mod tidy' and 'mise gogen' and commit the changes."
            exit 1
          fi

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up mise
        uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3.5.1

      - name: Run tests
        run: mise test
