name: Pull Request

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  formalities:
    name: Validate PR formalities
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          requireScope: false
          ignoreLabels: |
            dependabot

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up mise
        uses: jdx/mise-action@v3

      - name: Lint
        run: mise lint

      - name: Run go mod tidy
        run: go mod tidy

      - name: Run go generate
        run: mise gogen

      - name: Check for changes
        run: |
          if ! git diff --exit-code; then
            echo "::error::Files are not up to date. Please run 'go mod tidy' and 'mise gogen' and commit the changes."
            exit 1
          fi

      - name: Grype security check
        id: grype
        run: grype . -f medium --file grype.sarif
        continue-on-error: true

      - name: upload Grype scan SARIF report
        if: steps.grype.outcome == 'failure'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: grype.sarif

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up mise
        uses: jdx/mise-action@v3

      - name: Run tests
        run: mise test
