name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up mise
        uses: jdx/mise-action@v3

      - name: GPG prepare
        run: |
          base64 -d <<< "${{ secrets.GPG_KEYRING_BASE64 }}" > secring.gpg

      - name: Run GoReleaser
        run: |
          goreleaser release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Package OCI artifact
        run: |
          bash hack/helm-package.sh
        env:
          HELM_KEY_PASSPHRASE: ${{ secrets.HELM_KEY_PASSPHRASE }}
          SIGNING_KEY_EMAIL: ${{ secrets.SIGNING_KEY_EMAIL }}

      - name: Release OCI plugins with ORAS
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          oras push "$NAME:$VERSION" \
            --artifact-type application/vnd.helm.plugin.v1+json \
            "vendor-${VERSION}.tgz" \
            "vendor-${VERSION}.tgz.prov"

          oras push "$NAME:latest" \
            --artifact-type application/vnd.helm.plugin.v1+json \
            "vendor-${VERSION}.tgz" \
            "vendor-${VERSION}.tgz.prov"
        env:
          NAME: "ghcr.io/shikachuu/helm-vendor-plugin"
