name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up mise
        uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1

      - name: GPG prepare
        run: |
          base64 -d <<< "${{ secrets.GPG_KEYRING_BASE64 }}" > secring.gpg

      - name: Run GoReleaser
        run: |
          goreleaser release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Package OCI artifact
        run: |
          bash hack/helm-package.sh
        env:
          HELM_KEY_PASSPHRASE: ${{ secrets.HELM_KEY_PASSPHRASE }}
          SIGNING_KEY_EMAIL: ${{ secrets.SIGNING_KEY_EMAIL }}

      - name: Release OCI plugins with ORAS
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          # oras will include the full path to the artifact files, we must cd into the directory
          cd dist
          # upload the plugins to github's oci registry, the file names AND the repo name MUST match the plugin name in the plugin.yaml file!
          oras push "$NAME:$VERSION" \
            --artifact-type application/vnd.helm.plugin.v1+json \
            "helm-vendor-plugin-${VERSION}.tgz" \
            "helm-vendor-plugin-${VERSION}.tgz.prov"

          oras push "$NAME:latest" \
            --artifact-type application/vnd.helm.plugin.v1+json \
            "helm-vendor-plugin-${VERSION}.tgz" \
            "helm-vendor-plugin-${VERSION}.tgz.prov"
        env:
          NAME: "ghcr.io/shikachuu/helm-vendor-plugin"
